version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "url-shortener"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iyja643rw288"
s3_prefix = "url-shortener"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
